# Generated by Django 5.2.9 on 2025-12-25 18:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(max_length=100, unique=True)),
                ('customer_id', models.UUIDField()),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_phone', models.CharField(max_length=10)),
                ('pickup_address', models.CharField(max_length=255)),
                ('pickup_lat', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('pickup_lng', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('delivery_address', models.CharField(max_length=255)),
                ('delivery_lat', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('delivery_lng', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('preparing', 'Preparing'), ('ready', 'Ready'), ('picked_up', 'Picked Up'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=100)),
                ('priority', models.IntegerField(default=0)),
                ('estimated_delivery_time', models.DateTimeField(blank=True, null=True)),
                ('actual_delivery_time', models.DateTimeField(blank=True, null=True)),
                ('special_instructions', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'orders',
                'indexes': [models.Index(fields=['status'], name='orders_status_762191_idx'), models.Index(fields=['customer_id'], name='orders_custome_6c3a7f_idx'), models.Index(fields=['created_at'], name='orders_created_77e2b9_idx'), models.Index(fields=['order_number'], name='orders_order_n_1336be_idx'), models.Index(fields=['priority'], name='orders_priorit_dc6a0a_idx')],
            },
        ),
    ]
