# Generated by Django 6.0 on 2025-12-27 18:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deliveries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rider',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10, unique=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('vehicle_type', models.CharField(choices=[('bike', 'Bike'), ('car', 'Car'), ('scooter', 'Scooter')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('current_status', models.CharField(choices=[('offline', 'Offline'), ('busy', 'Busy'), ('available', 'Available')], default='offline', max_length=10)),
            ],
            options={
                'db_table': 'riders',
                'indexes': [models.Index(fields=['current_status'], name='riders_current_3f2025_idx'), models.Index(fields=['is_active'], name='riders_is_acti_c414a3_idx')],
            },
        ),
        migrations.CreateModel(
            name='RiderLocation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lat', models.DecimalField(decimal_places=8, max_digits=10)),
                ('lng', models.DecimalField(decimal_places=8, max_digits=10)),
                ('accuracy', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('speed', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('heading', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('battery_level', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('delivery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rider_locations', to='deliveries.delivery')),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='riders.rider')),
            ],
            options={
                'db_table': 'rider_locations',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['rider', '-timestamp'], name='rider_locat_rider_i_d148ed_idx'), models.Index(fields=['delivery'], name='rider_locat_deliver_a3b42b_idx')],
            },
        ),
    ]
