# Generated by Django 6.0 on 2025-12-27 18:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deliveries', '0002_initial'),
        ('orders', '0001_initial'),
        ('riders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('order_received', 'ORDER_RECEIVED'), ('preparing', 'Preparing'), ('ready_to_deliver', 'Ready to Deliver'), ('rider_assigned', 'Rider Assigned'), ('pickup_started', 'Pickup Started'), ('picked_up', 'Picked Up'), ('in_transit', 'In Transit'), ('nearby', 'Nearby'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], max_length=100)),
                ('event_data', models.JSONField(blank=True, default=dict)),
                ('location_lat', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('location_long', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='deliveries.delivery')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='orders.order')),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='riders.rider')),
            ],
            options={
                'db_table': 'delivery_events',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['delivery'], name='delivery_ev_deliver_67624d_idx'), models.Index(fields=['event_type'], name='delivery_ev_event_t_8b60b9_idx'), models.Index(fields=['timestamp'], name='delivery_ev_timesta_b0cff2_idx')],
            },
        ),
    ]
