# Generated by Django 6.0 on 2025-12-27 18:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deliveries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_id', models.UUIDField()),
                ('recipient_type', models.CharField(choices=[('customer', 'Customer'), ('rider', 'Rider')], max_length=50)),
                ('notification_type', models.CharField(max_length=100)),
                ('title', models.CharField(blank=True, max_length=50)),
                ('message', models.TextField(blank=True)),
                ('is_read', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('delivery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='deliveries.delivery')),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['recipient_id', 'is_read'], name='notificatio_recipie_583549_idx')],
            },
        ),
    ]
