# Generated by Django 6.0 on 2025-12-27 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deliveries', '0001_initial'),
        ('orders', '0001_initial'),
        ('riders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchdelivery',
            name='rider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_deliveries', to='riders.rider'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='orders.order'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='rider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='riders.rider'),
        ),
        migrations.AddIndex(
            model_name='batchdelivery',
            index=models.Index(fields=['status'], name='batch_deliv_status_445865_idx'),
        ),
        migrations.AddIndex(
            model_name='batchdelivery',
            index=models.Index(fields=['rider'], name='batch_deliv_rider_i_138f55_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['status'], name='deliveries_status_c2a7cc_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['rider'], name='deliveries_rider_i_39e76a_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['order'], name='deliveries_order_i_744a2b_idx'),
        ),
    ]
