# Generated by Django 6.0 on 2026-01-02 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('assigned', 'Assigned'), ('accepted', 'Accepted'), ('denied', 'Denied'), ('in_progress', 'In Progress'), ('collected', 'Collected'), ('completed', 'Completed'), ('failed', 'Failed')], default='assigned', max_length=50),
        ),
    ]
