# Generated by Django 6.0 on 2026-01-02 15:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0002_add_dead_letter_queue'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='deadletterqueue',
            new_name='dead_letter_status_d88d36_idx',
            old_name='dead_letter_status_idx',
        ),
        migrations.RenameIndex(
            model_name='deadletterqueue',
            new_name='dead_letter_next_re_b5149c_idx',
            old_name='dead_letter_next_retry_idx',
        ),
        migrations.RenameIndex(
            model_name='deadletterqueue',
            new_name='dead_letter_topic_bf9129_idx',
            old_name='dead_letter_topic_idx',
        ),
        migrations.AlterField(
            model_name='deadletterqueue',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
