# Generated by Django 6.0 on 2026-01-02 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0003_add_simulation_state_fields'),
        ('deliveries', '0003_rename_dead_letter_status_idx_dead_letter_status_d88d36_idx_and_more'),
    ]

    operations = [
    ]
